### ISSUE TITLE
No proxy connection messages

### ISSUE THREAD

**Issue by alexratman** [addstar/geSuit#15]
I believe this is a duplicate of #11 but cannot be sure.

I am having an issue whereby the proxy join messages are not being displayed; but the proxy leave messages are displaying as expected.

PLAYER_CONNECT_PROXY | not displayed in console; not displayed in chat.
PLAYER_DISCONNECT_PROXY | displayed in console; displayed in chat.

[Proxy Log - Startup](http://paste.ubuntu.com/10626944/)
[Proxy Log - Player join event](http://paste.ubuntu.com/10626870/)
[Proxy Log - Player leave event](http://paste.ubuntu.com/10626978/) - Note that we are using "LEAVE MESSAGE" as a debug leave message
[Server Log - Startup](http://paste.ubuntu.com/10626937/)
[Server Log - Player join event](http://paste.ubuntu.com/10626901/)

[Config.yml](http://paste.ubuntu.com/10626971/)
[Messages.yml](http://paste.ubuntu.com/10626982/)

**Bungeecord version:** git:Bungeecord-Bootstrap:1.8-SNAPSHOT:"f2d17cb":1052 by md_5
**Spigot version:** git-Spigot-c3c767f-33d5de3 (MC:1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

All versions of GeSuit are latest from your build server.

**Comment by addstar** [comment]
Oh wow! I just checked the code and the PLAYER_CONNECT_PROXY message is never used.. it was accidentally removed long ago in change b44d083bbfa79facf8a8db5cb62e11ef22d61167 (Aug 8, 2014) :open_mouth: 

Sadly, we never noticed because we use another plugin to handle proxy join/quit messages. It's an easy fix to add, I'll do this shortly. Thanks for all the thorough info, much appreciated!

**Comment by addstar** [comment]
Fixed in build 85 :grin:
