### ISSUE TITLE
Player name changes tracking bug

### ISSUE THREAD

**Issue by Absentee23** [addstar/geSuit#16]
In /namehistory, if a player (original NameA) changes their name (NameB), then changes it back to their original name (NameA), it appears in /namehistory with only two names and makes the dates appear as if their original name was NameB, and they changed it one time to NameA.

I'm not sure how this could be handled though, as there may be some issues with duplicate values in the playername column.

**Comment by addstar** [comment]
Unfortunately, this is one of the drawbacks of using the existing tracking table to track name changes. We didn't want to create a whole new table for this since we already stored the information inside the tracking table. Sorry, but I don't see any way around this issue, unless we make a separate table just for name history.
