### ISSUE TITLE
Portals stop working after some time.

### ISSUE THREAD

**Issue by Kainzo** [addstar/geSuit#18]
http://pastie.org/private/z4zwzdcxsjcf7eyszdd4dq

Latest BungeeCord
Latest geSuite (and plugins) on Addstar Jenkins

It seems to be fixed when the player disconnects and reconnects.

**Comment by Kainzo** [comment]
This is stil ongoing.

**Comment by addstar** [comment]
This is not specific to portals. I believe this problem happens when the user times out and reconnects before the disconnect event fires.

From what I've seen this is what happens:
1. Player logs in, everything is fine.
2. Player lags and their client disconnects but was still seen as "connected" on the proxy.
3. Player tries to login again, everything is fine.
4. Previous disconnect event fires and geSuit removes the player from the "online players" list.

This is where all the problems come from. It is very common with mobile connections and connections with very poor reliability. Once this situation happens, the player will be unable to do anything in geSuit and almost all commands will have errors. The only way to resolve the situation is to disconnect properly and reconnect.

To confirm this, you need to carefully check the corresponding proxy + server logs. The "player is null" error is a result of the condition and is not the problem itself. You need to look earlier in the logs from when they connected and reconnected.

From what I understand, the only way to fix this is to reject connections for players if they are already seen as "online" in the proxy. If this continues to be a big problem, we can look into it.
