### ISSUE TITLE
/portals command not displaying a full list of portals.

### ISSUE THREAD

**Issue by elliswin** [addstar/geSuit#31]
I am experiencing a problem with the /portals command not displaying a full list of all the portals on the server.

Currently this is only displaying 1 portal on the Paintball server, yet when I check phpMyAdmin and access the data base, I can see all of the portals on the servers.

We are using build #93 of geSuite and geSuitPortals version 0.1.1b-4

Any advice on resolving this would be appreciated.

Ellis Win.

**Comment by addstar** [comment]
It looks like you removed a server (or changed it's name) that had a portal on it.. this part of your logs (sent to me directly) is the part that is important:

```09.07 22:03:32 [Server] SEVERE Location has no Server, this should never happen. Please check```

It would be good if it actually told you which server was missing, but unfortunately it doesn't.

It might help to understand a bit about how portals are loaded on each server. When the first player joins each server (after a restart), the proxy sends the full list of portals to that server. You can see here that geSuit is crashing while trying to read the list of portals because one of the server names doesn't exist.. this means you have a portal in the DB, marked against a server that has been removed.

This situation should be handled better, and I'll add in a fix for this. But in the mean time, browse over your portal list in the DB and remove any records for non-existent servers.

**Comment by addstar** [comment]
Sorry, I just re-read the stack trace again.. it looks like it's actually a problem in your `spawns` table. You should check the records in both tables for any incorrect or missing `server` fields.
